FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update && apt-get -y install vim python3 python3-distutils bind9 bind9-utils

WORKDIR /root

COPY rpz_manager.py /usr/local/bin/rpz-manager
COPY test /root/test
RUN /root/test/system/setup_ubuntu.sh

ENV NAMED_DIR=/etc/bind NAMED_USER=bind
RUN useradd -m -G $NAMED_USER unprivileged

CMD ["/root/test/system/entrypoint.sh"]
