name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: run unit tests
        run: python3 -m unittest -v test/unit/tests.py

  system-test:
    runs-on: ubuntu-latest

    needs: unit-test

    strategy:
      matrix:
        os: [centos, ubuntu]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache docker images
        uses: actions/cache@v2
        id: docker-cache
        with:
          path: rpz-manager-${{ matrix.os }}.tar
          key: ${{ matrix.os }}-${{ hashFiles('Dockerfile.*') }}

      - name: import docker image if available
        if: steps.docker-cache.outputs.cache-hit == 'true'
        run: docker import rpz-manager-${{ matrix.os }}.tar rpz-manager:${{ matrix.os }}

      - name: build test image
        run: docker build . -f Dockerfile.${{ matrix.os }} -t rpz-manager:${{ matrix.os }}

      - name: run test image
        run: docker run -t rpz-manager

      - name: export docker image if needed
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: docker save rpz-manager > rpz-manager-${{ matrix.os }}.tar
